#!/usr/bin/env node
/* Seed the Supabase `courses` catalogue from the built-in data/course-*.js files.
   IDs use the same slug() as js/app.js so catalogue rows match FEATURED_IDS.

   Default:            node scripts/seed-courses.mjs
     → writes supabase/seed.sql (idempotent upserts; run via `supabase db push`
       companion or paste into the dashboard SQL editor)

   Direct push:        SUPABASE_URL=https://<ref>.supabase.co \
                       SUPABASE_SERVICE_ROLE_KEY=... \
                       node scripts/seed-courses.mjs --push
     → upserts straight into the live `courses` table via PostgREST */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const slug = (s) => (s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const courses = [];
for (const f of readdirSync(join(root, "data")).filter((f) => /^course-.*\.js$/.test(f))) {
  const src = readFileSync(join(root, "data", f), "utf8");
  // files are `window.TDP_COURSE_X = {json};` — take everything between the
  // first `=` and the final `;`
  const body = src.slice(src.indexOf("=") + 1).trim().replace(/;\s*$/, "");
  let c;
  try { c = JSON.parse(body); }
  catch (e) { console.error(`skip ${f}: not parseable as JSON (${e.message})`); continue; }
  if (!c?.course?.name || !Array.isArray(c.holes) || !c.holes.length) {
    console.error(`skip ${f}: missing course.name or holes`);
    continue;
  }
  courses.push({
    id: slug(c.course.name),
    name: c.course.name,
    location: c.course.location || null,
    geometry: c,
    source: "built-in",
  });
  console.log(`✓ ${f} → ${slug(c.course.name)} (${c.holes.length} holes)`);
}

if (!courses.length) { console.error("no courses found — nothing to seed"); process.exit(1); }

if (process.argv.includes("--push")) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error("--push needs SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY env vars");
    process.exit(1);
  }
  const res = await fetch(`${url.replace(/\/$/, "")}/rest/v1/courses?on_conflict=id`, {
    method: "POST",
    headers: {
      apikey: key,
      authorization: `Bearer ${key}`,
      "content-type": "application/json",
      prefer: "resolution=merge-duplicates",
    },
    body: JSON.stringify(courses),
  });
  if (!res.ok) { console.error(`push failed: ${res.status} ${await res.text()}`); process.exit(1); }
  console.log(`pushed ${courses.length} courses to ${url}`);
} else {
  const esc = (s) => s.replace(/'/g, "''");
  const rows = courses.map((c) =>
    `('${esc(c.id)}', '${esc(c.name)}', ${c.location ? `'${esc(c.location)}'` : "null"}, '${esc(JSON.stringify(c.geometry))}'::jsonb, 'built-in')`
  );
  const sql = `-- generated by scripts/seed-courses.mjs — do not edit by hand
insert into public.courses (id, name, location, geometry, source)
values
${rows.join(",\n")}
on conflict (id) do update
  set name = excluded.name,
      location = excluded.location,
      geometry = excluded.geometry;
`;
  const out = join(root, "supabase", "seed.sql");
  writeFileSync(out, sql);
  console.log(`wrote ${out} (${courses.length} courses, ${(sql.length / 1024).toFixed(0)} kB)`);
}
